languageCode = "en"
languageName = "English"
weight = 1
title = "w6rst"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "My awesome website"
dateFormat = "2 January 2006"
author = { name = "w6rst", image = "img/avatar.jpeg", headline = "", bio = "", links = [ { github = "https://github.com/w6rstaimn" }, { x-twitter = "https://twitter.com/burufugu" } ] }
logo = "pikachu.gif"

